// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(DS3CoreFFIFFI)
    import DS3CoreFFIFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ds3_models_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ds3_models_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    []
}

private func writeBytes(_ writer: inout [UInt8], _ byteArr: some Sequence<UInt8>) {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt(_ writer: inout [UInt8], _ value: some FixedWidthInteger) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}
/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: "Reading the requested value would read past the end of the buffer"
        case .incompleteData: "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: "The object in the handle map has been dropped already"
        case let .rustPanic(message): message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> some Swift.Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> some Swift.Error)?
) throws -> T {
    uniffiEnsureDs3ModelsInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> some Swift.Error)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
private let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
private let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

private final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            doInsert(obj)
        }
    }

    /// Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        try lift(readInt(&buf))
    }

    static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        try lift(readInt(&buf))
    }

    static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

/**
 * An account in the Cubbit DS3 ecosystem.
 */
public struct Account: Equatable, Hashable {
    /**
     * The account unique identifier.
     */
    public var id: String
    /**
     * The user's first name.
     */
    public var firstName: String
    /**
     * The user's last name.
     */
    public var lastName: String
    /**
     * Whether the account is internal.
     */
    public var isInternal: Bool
    /**
     * Whether the account is banned.
     */
    public var isBanned: Bool
    /**
     * When the account was created (ISO 8601).
     */
    public var createdAt: String
    /**
     * When the account was deleted, if applicable.
     */
    public var deletedAt: String?
    /**
     * When the account was banned, if applicable.
     */
    public var bannedAt: String?
    /**
     * Maximum number of projects allowed.
     */
    public var maxAllowedProjects: Int32
    /**
     * The account's email addresses.
     */
    public var emails: [AccountEmail]
    /**
     * Whether two-factor authentication is enabled.
     */
    public var isTwoFactorEnabled: Bool
    /**
     * The tenant identifier.
     */
    public var tenantId: String
    /**
     * The S3 endpoint gateway URL.
     */
    public var endpointGateway: String
    /**
     * The authentication provider.
     */
    public var authProvider: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The account unique identifier.
         */ id: String,
        /* 
            * The user's first name.
            */ firstName: String,
        /* 
            * The user's last name.
            */ lastName: String,
        /* 
            * Whether the account is internal.
            */ isInternal: Bool,
        /* 
            * Whether the account is banned.
            */ isBanned: Bool,
        /* 
            * When the account was created (ISO 8601).
            */ createdAt: String,
        /* 
            * When the account was deleted, if applicable.
            */ deletedAt: String?,
        /* 
            * When the account was banned, if applicable.
            */ bannedAt: String?,
        /* 
            * Maximum number of projects allowed.
            */ maxAllowedProjects: Int32,
        /* 
            * The account's email addresses.
            */ emails: [AccountEmail],
        /* 
            * Whether two-factor authentication is enabled.
            */ isTwoFactorEnabled: Bool,
        /* 
            * The tenant identifier.
            */ tenantId: String,
        /* 
            * The S3 endpoint gateway URL.
            */ endpointGateway: String,
        /* 
            * The authentication provider.
            */ authProvider: String
    ) {
        self.id = id
        self.firstName = firstName
        self.lastName = lastName
        self.isInternal = isInternal
        self.isBanned = isBanned
        self.createdAt = createdAt
        self.deletedAt = deletedAt
        self.bannedAt = bannedAt
        self.maxAllowedProjects = maxAllowedProjects
        self.emails = emails
        self.isTwoFactorEnabled = isTwoFactorEnabled
        self.tenantId = tenantId
        self.endpointGateway = endpointGateway
        self.authProvider = authProvider
    }
}

#if compiler(>=6)
    extension Account: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccount: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Account {
        try Account(
            id: FfiConverterString.read(from: &buf),
            firstName: FfiConverterString.read(from: &buf),
            lastName: FfiConverterString.read(from: &buf),
            isInternal: FfiConverterBool.read(from: &buf),
            isBanned: FfiConverterBool.read(from: &buf),
            createdAt: FfiConverterString.read(from: &buf),
            deletedAt: FfiConverterOptionString.read(from: &buf),
            bannedAt: FfiConverterOptionString.read(from: &buf),
            maxAllowedProjects: FfiConverterInt32.read(from: &buf),
            emails: FfiConverterSequenceTypeAccountEmail.read(from: &buf),
            isTwoFactorEnabled: FfiConverterBool.read(from: &buf),
            tenantId: FfiConverterString.read(from: &buf),
            endpointGateway: FfiConverterString.read(from: &buf),
            authProvider: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Account, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.firstName, into: &buf)
        FfiConverterString.write(value.lastName, into: &buf)
        FfiConverterBool.write(value.isInternal, into: &buf)
        FfiConverterBool.write(value.isBanned, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterOptionString.write(value.deletedAt, into: &buf)
        FfiConverterOptionString.write(value.bannedAt, into: &buf)
        FfiConverterInt32.write(value.maxAllowedProjects, into: &buf)
        FfiConverterSequenceTypeAccountEmail.write(value.emails, into: &buf)
        FfiConverterBool.write(value.isTwoFactorEnabled, into: &buf)
        FfiConverterString.write(value.tenantId, into: &buf)
        FfiConverterString.write(value.endpointGateway, into: &buf)
        FfiConverterString.write(value.authProvider, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccount_lift(_ buf: RustBuffer) throws -> Account {
    try FfiConverterTypeAccount.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccount_lower(_ value: Account) -> RustBuffer {
    FfiConverterTypeAccount.lower(value)
}

/**
 * An email address associated with a Cubbit account.
 */
public struct AccountEmail: Equatable, Hashable {
    /**
     * The email record identifier.
     */
    public var id: String
    /**
     * The email address.
     */
    public var email: String
    /**
     * Whether this is the default email for the account.
     */
    public var isDefault: Bool
    /**
     * When the email was created (ISO 8601).
     */
    public var createdAt: String
    /**
     * Whether the email has been verified.
     */
    public var isVerified: Bool
    /**
     * The tenant identifier.
     */
    public var tenantId: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The email record identifier.
         */ id: String,
        /* 
            * The email address.
            */ email: String,
        /* 
            * Whether this is the default email for the account.
            */ isDefault: Bool,
        /* 
            * When the email was created (ISO 8601).
            */ createdAt: String,
        /* 
            * Whether the email has been verified.
            */ isVerified: Bool,
        /* 
            * The tenant identifier.
            */ tenantId: String
    ) {
        self.id = id
        self.email = email
        self.isDefault = isDefault
        self.createdAt = createdAt
        self.isVerified = isVerified
        self.tenantId = tenantId
    }
}

#if compiler(>=6)
    extension AccountEmail: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountEmail: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AccountEmail {
        try AccountEmail(
            id: FfiConverterString.read(from: &buf),
            email: FfiConverterString.read(from: &buf),
            isDefault: FfiConverterBool.read(from: &buf),
            createdAt: FfiConverterString.read(from: &buf),
            isVerified: FfiConverterBool.read(from: &buf),
            tenantId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AccountEmail, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.email, into: &buf)
        FfiConverterBool.write(value.isDefault, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterBool.write(value.isVerified, into: &buf)
        FfiConverterString.write(value.tenantId, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountEmail_lift(_ buf: RustBuffer) throws -> AccountEmail {
    try FfiConverterTypeAccountEmail.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountEmail_lower(_ value: AccountEmail) -> RustBuffer {
    FfiConverterTypeAccountEmail.lower(value)
}

/**
 * An authenticated session containing an access token and refresh token.
 *
 * Matches the Swift `AccountSession` JSON schema where `refreshToken` is
 * serialized in camelCase (not snake_case).
 */
public struct AccountSession: Equatable, Hashable {
    /**
     * The current access token.
     */
    public var token: Token
    /**
     * The refresh token string.
     */
    public var refreshToken: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The current access token.
         */ token: Token,
        /* 
            * The refresh token string.
            */ refreshToken: String
    ) {
        self.token = token
        self.refreshToken = refreshToken
    }
}

#if compiler(>=6)
    extension AccountSession: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountSession: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AccountSession {
        try AccountSession(
            token: FfiConverterTypeToken.read(from: &buf),
            refreshToken: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AccountSession, into buf: inout [UInt8]) {
        FfiConverterTypeToken.write(value.token, into: &buf)
        FfiConverterString.write(value.refreshToken, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountSession_lift(_ buf: RustBuffer) throws -> AccountSession {
    try FfiConverterTypeAccountSession.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountSession_lower(_ value: AccountSession) -> RustBuffer {
    FfiConverterTypeAccountSession.lower(value)
}

/**
 * Information about an S3 bucket.
 */
public struct BucketInfo: Equatable, Hashable {
    /**
     * The bucket name.
     */
    public var name: String
    /**
     * When the bucket was created (ISO 8601 string), if available.
     */
    public var creationDate: String?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The bucket name.
         */ name: String,
        /* 
            * When the bucket was created (ISO 8601 string), if available.
            */ creationDate: String?
    ) {
        self.name = name
        self.creationDate = creationDate
    }
}

#if compiler(>=6)
    extension BucketInfo: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeBucketInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BucketInfo {
        try BucketInfo(
            name: FfiConverterString.read(from: &buf),
            creationDate: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: BucketInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.creationDate, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeBucketInfo_lift(_ buf: RustBuffer) throws -> BucketInfo {
    try FfiConverterTypeBucketInfo.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeBucketInfo_lower(_ value: BucketInfo) -> RustBuffer {
    FfiConverterTypeBucketInfo.lower(value)
}

/**
 * A security challenge issued by the Cubbit IAM server.
 */
public struct Challenge: Equatable, Hashable {
    /**
     * The challenge string to be signed.
     */
    public var challenge: String
    /**
     * The salt used in key derivation.
     */
    public var salt: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The challenge string to be signed.
         */ challenge: String,
        /* 
            * The salt used in key derivation.
            */ salt: String
    ) {
        self.challenge = challenge
        self.salt = salt
    }
}

#if compiler(>=6)
    extension Challenge: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeChallenge: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Challenge {
        try Challenge(
            challenge: FfiConverterString.read(from: &buf),
            salt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Challenge, into buf: inout [UInt8]) {
        FfiConverterString.write(value.challenge, into: &buf)
        FfiConverterString.write(value.salt, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeChallenge_lift(_ buf: RustBuffer) throws -> Challenge {
    try FfiConverterTypeChallenge.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeChallenge_lower(_ value: Challenge) -> RustBuffer {
    FfiConverterTypeChallenge.lower(value)
}

/**
 * Result of a single completed multipart upload part.
 */
public struct CompletedPartResult: Equatable, Hashable {
    /**
     * The part number (1-based).
     */
    public var partNumber: Int32
    /**
     * The ETag returned by S3 for this part.
     */
    public var etag: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The part number (1-based).
         */ partNumber: Int32,
        /* 
            * The ETag returned by S3 for this part.
            */ etag: String
    ) {
        self.partNumber = partNumber
        self.etag = etag
    }
}

#if compiler(>=6)
    extension CompletedPartResult: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompletedPartResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompletedPartResult {
        try CompletedPartResult(
            partNumber: FfiConverterInt32.read(from: &buf),
            etag: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CompletedPartResult, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.partNumber, into: &buf)
        FfiConverterString.write(value.etag, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletedPartResult_lift(_ buf: RustBuffer) throws -> CompletedPartResult {
    try FfiConverterTypeCompletedPartResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCompletedPartResult_lower(_ value: CompletedPartResult) -> RustBuffer {
    FfiConverterTypeCompletedPartResult.lower(value)
}

/**
 * An S3 API key in the Cubbit DS3 ecosystem.
 *
 * The `secret_key` is only present when a key is first created (the server
 * returns it once). When listing existing keys, `secret_key` is `None`.
 * The `created_at` field is stored as an ISO 8601 string.
 */
public struct Ds3ApiKey: Equatable, Hashable {
    /**
     * The name of the API key.
     */
    public var name: String
    /**
     * The S3 access key ID (public key).
     */
    public var apiKey: String
    /**
     * The S3 secret access key (private key), only present on creation.
     */
    public var secretKey: String?
    /**
     * When the API key was created (ISO 8601 string).
     */
    public var createdAt: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The name of the API key.
         */ name: String,
        /* 
            * The S3 access key ID (public key).
            */ apiKey: String,
        /* 
            * The S3 secret access key (private key), only present on creation.
            */ secretKey: String?,
        /* 
            * When the API key was created (ISO 8601 string).
            */ createdAt: String
    ) {
        self.name = name
        self.apiKey = apiKey
        self.secretKey = secretKey
        self.createdAt = createdAt
    }
}

#if compiler(>=6)
    extension Ds3ApiKey: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDS3ApiKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Ds3ApiKey {
        try Ds3ApiKey(
            name: FfiConverterString.read(from: &buf),
            apiKey: FfiConverterString.read(from: &buf),
            secretKey: FfiConverterOptionString.read(from: &buf),
            createdAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Ds3ApiKey, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.apiKey, into: &buf)
        FfiConverterOptionString.write(value.secretKey, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDS3ApiKey_lift(_ buf: RustBuffer) throws -> Ds3ApiKey {
    try FfiConverterTypeDS3ApiKey.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDS3ApiKey_lower(_ value: Ds3ApiKey) -> RustBuffer {
    FfiConverterTypeDS3ApiKey.lower(value)
}

/**
 * FFI-friendly version of `DiffResult` using `Vec<String>` instead of `HashSet`.
 *
 * UniFFI does not support `HashSet` in Records. This type provides a
 * conversion from the native `DiffResult` for crossing the FFI boundary.
 */
public struct DiffResultRecord: Equatable, Hashable {
    /**
     * Keys that are new or have a different ETag compared to the local tree.
     */
    public var newOrModified: [String]
    /**
     * Keys that exist locally but no longer exist remotely.
     */
    public var deleted: [String]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Keys that are new or have a different ETag compared to the local tree.
         */ newOrModified: [String],
        /* 
            * Keys that exist locally but no longer exist remotely.
            */ deleted: [String]
    ) {
        self.newOrModified = newOrModified
        self.deleted = deleted
    }
}

#if compiler(>=6)
    extension DiffResultRecord: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiffResultRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DiffResultRecord {
        try DiffResultRecord(
            newOrModified: FfiConverterSequenceString.read(from: &buf),
            deleted: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: DiffResultRecord, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.newOrModified, into: &buf)
        FfiConverterSequenceString.write(value.deleted, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDiffResultRecord_lift(_ buf: RustBuffer) throws -> DiffResultRecord {
    try FfiConverterTypeDiffResultRecord.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDiffResultRecord_lower(_ value: DiffResultRecord) -> RustBuffer {
    FfiConverterTypeDiffResultRecord.lower(value)
}

/**
 * An IAM User in the Cubbit DS3 ecosystem.
 */
public struct IamUser: Equatable, Hashable {
    /**
     * The IAM user ID.
     */
    public var id: String
    /**
     * The IAM username.
     */
    public var username: String
    /**
     * Whether the user is a root user.
     */
    public var isRoot: Bool

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The IAM user ID.
         */ id: String,
        /* 
            * The IAM username.
            */ username: String,
        /* 
            * Whether the user is a root user.
            */ isRoot: Bool
    ) {
        self.id = id
        self.username = username
        self.isRoot = isRoot
    }
}

#if compiler(>=6)
    extension IamUser: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeIAMUser: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IamUser {
        try IamUser(
            id: FfiConverterString.read(from: &buf),
            username: FfiConverterString.read(from: &buf),
            isRoot: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: IamUser, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterBool.write(value.isRoot, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeIAMUser_lift(_ buf: RustBuffer) throws -> IamUser {
    try FfiConverterTypeIAMUser.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeIAMUser_lower(_ value: IamUser) -> RustBuffer {
    FfiConverterTypeIAMUser.lower(value)
}

/**
 * Context for an active multipart upload.
 */
public struct MultipartUploadContext: Equatable, Hashable {
    /**
     * The target bucket.
     */
    public var bucket: String
    /**
     * The target object key.
     */
    public var key: String
    /**
     * The upload ID assigned by S3.
     */
    public var uploadId: String
    /**
     * The total file size in bytes.
     */
    public var totalSize: Int64

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The target bucket.
         */ bucket: String,
        /* 
            * The target object key.
            */ key: String,
        /* 
            * The upload ID assigned by S3.
            */ uploadId: String,
        /* 
            * The total file size in bytes.
            */ totalSize: Int64
    ) {
        self.bucket = bucket
        self.key = key
        self.uploadId = uploadId
        self.totalSize = totalSize
    }
}

#if compiler(>=6)
    extension MultipartUploadContext: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeMultipartUploadContext: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MultipartUploadContext {
        try MultipartUploadContext(
            bucket: FfiConverterString.read(from: &buf),
            key: FfiConverterString.read(from: &buf),
            uploadId: FfiConverterString.read(from: &buf),
            totalSize: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MultipartUploadContext, into buf: inout [UInt8]) {
        FfiConverterString.write(value.bucket, into: &buf)
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.uploadId, into: &buf)
        FfiConverterInt64.write(value.totalSize, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeMultipartUploadContext_lift(_ buf: RustBuffer) throws -> MultipartUploadContext {
    try FfiConverterTypeMultipartUploadContext.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeMultipartUploadContext_lower(_ value: MultipartUploadContext) -> RustBuffer {
    FfiConverterTypeMultipartUploadContext.lower(value)
}

/**
 * A project in the Cubbit DS3 ecosystem.
 *
 * JSON keys use a `project_` prefix for most fields, matching the API
 * response schema and the Swift `CodingKeys`.
 */
public struct Project: Equatable, Hashable {
    /**
     * The project unique ID.
     */
    public var id: String
    /**
     * The project name.
     */
    public var name: String
    /**
     * The project description.
     */
    public var description: String
    /**
     * The project email (used for ACL operations, not a real address).
     */
    public var email: String
    /**
     * When the project was created (ISO 8601).
     */
    public var createdAt: String
    /**
     * When the project was banned, if applicable.
     */
    public var bannedAt: String?
    /**
     * The project image URL, if set.
     */
    public var imageUrl: String?
    /**
     * The project tenant ID.
     */
    public var tenantId: String
    /**
     * The root account email, if set.
     */
    public var rootAccountEmail: String?
    /**
     * The IAM users belonging to this project.
     */
    public var users: [IamUser]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The project unique ID.
         */ id: String,
        /* 
            * The project name.
            */ name: String,
        /* 
            * The project description.
            */ description: String,
        /* 
            * The project email (used for ACL operations, not a real address).
            */ email: String,
        /* 
            * When the project was created (ISO 8601).
            */ createdAt: String,
        /* 
            * When the project was banned, if applicable.
            */ bannedAt: String?,
        /* 
            * The project image URL, if set.
            */ imageUrl: String?,
        /* 
            * The project tenant ID.
            */ tenantId: String,
        /* 
            * The root account email, if set.
            */ rootAccountEmail: String?,
        /* 
            * The IAM users belonging to this project.
            */ users: [IamUser]
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.email = email
        self.createdAt = createdAt
        self.bannedAt = bannedAt
        self.imageUrl = imageUrl
        self.tenantId = tenantId
        self.rootAccountEmail = rootAccountEmail
        self.users = users
    }
}

#if compiler(>=6)
    extension Project: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeProject: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Project {
        try Project(
            id: FfiConverterString.read(from: &buf),
            name: FfiConverterString.read(from: &buf),
            description: FfiConverterString.read(from: &buf),
            email: FfiConverterString.read(from: &buf),
            createdAt: FfiConverterString.read(from: &buf),
            bannedAt: FfiConverterOptionString.read(from: &buf),
            imageUrl: FfiConverterOptionString.read(from: &buf),
            tenantId: FfiConverterString.read(from: &buf),
            rootAccountEmail: FfiConverterOptionString.read(from: &buf),
            users: FfiConverterSequenceTypeIAMUser.read(from: &buf)
        )
    }

    public static func write(_ value: Project, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.email, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterOptionString.write(value.bannedAt, into: &buf)
        FfiConverterOptionString.write(value.imageUrl, into: &buf)
        FfiConverterString.write(value.tenantId, into: &buf)
        FfiConverterOptionString.write(value.rootAccountEmail, into: &buf)
        FfiConverterSequenceTypeIAMUser.write(value.users, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeProject_lift(_ buf: RustBuffer) throws -> Project {
    try FfiConverterTypeProject.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeProject_lower(_ value: Project) -> RustBuffer {
    FfiConverterTypeProject.lower(value)
}

/**
 * Result metadata from a download operation (FFI-friendly version).
 */
public struct S3DownloadResult: Equatable, Hashable {
    /**
     * The object's ETag (normalized, without quotes).
     */
    public var etag: String?
    /**
     * The MIME content type.
     */
    public var contentType: String?
    /**
     * When the object was last modified.
     */
    public var lastModified: String?
    /**
     * Content length in bytes.
     */
    public var contentLength: Int64

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The object's ETag (normalized, without quotes).
         */ etag: String?,
        /* 
            * The MIME content type.
            */ contentType: String?,
        /* 
            * When the object was last modified.
            */ lastModified: String?,
        /* 
            * Content length in bytes.
            */ contentLength: Int64
    ) {
        self.etag = etag
        self.contentType = contentType
        self.lastModified = lastModified
        self.contentLength = contentLength
    }
}

#if compiler(>=6)
    extension S3DownloadResult: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeS3DownloadResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> S3DownloadResult {
        try S3DownloadResult(
            etag: FfiConverterOptionString.read(from: &buf),
            contentType: FfiConverterOptionString.read(from: &buf),
            lastModified: FfiConverterOptionString.read(from: &buf),
            contentLength: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: S3DownloadResult, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.etag, into: &buf)
        FfiConverterOptionString.write(value.contentType, into: &buf)
        FfiConverterOptionString.write(value.lastModified, into: &buf)
        FfiConverterInt64.write(value.contentLength, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeS3DownloadResult_lift(_ buf: RustBuffer) throws -> S3DownloadResult {
    try FfiConverterTypeS3DownloadResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeS3DownloadResult_lower(_ value: S3DownloadResult) -> RustBuffer {
    FfiConverterTypeS3DownloadResult.lower(value)
}

/**
 * Result of an S3 ListObjectsV2 call.
 */
public struct S3ListingResult: Equatable, Hashable {
    /**
     * The objects returned in this page.
     */
    public var objects: [S3ObjectSummary]
    /**
     * Common prefixes (virtual "directories") when using a delimiter.
     */
    public var commonPrefixes: [String]
    /**
     * Token for fetching the next page, if the result is truncated.
     */
    public var nextContinuationToken: String?
    /**
     * Whether there are more results to fetch.
     */
    public var isTruncated: Bool

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The objects returned in this page.
         */ objects: [S3ObjectSummary],
        /* 
            * Common prefixes (virtual "directories") when using a delimiter.
            */ commonPrefixes: [String],
        /* 
            * Token for fetching the next page, if the result is truncated.
            */ nextContinuationToken: String?,
        /* 
            * Whether there are more results to fetch.
            */ isTruncated: Bool
    ) {
        self.objects = objects
        self.commonPrefixes = commonPrefixes
        self.nextContinuationToken = nextContinuationToken
        self.isTruncated = isTruncated
    }
}

#if compiler(>=6)
    extension S3ListingResult: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeS3ListingResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> S3ListingResult {
        try S3ListingResult(
            objects: FfiConverterSequenceTypeS3ObjectSummary.read(from: &buf),
            commonPrefixes: FfiConverterSequenceString.read(from: &buf),
            nextContinuationToken: FfiConverterOptionString.read(from: &buf),
            isTruncated: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: S3ListingResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeS3ObjectSummary.write(value.objects, into: &buf)
        FfiConverterSequenceString.write(value.commonPrefixes, into: &buf)
        FfiConverterOptionString.write(value.nextContinuationToken, into: &buf)
        FfiConverterBool.write(value.isTruncated, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeS3ListingResult_lift(_ buf: RustBuffer) throws -> S3ListingResult {
    try FfiConverterTypeS3ListingResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeS3ListingResult_lower(_ value: S3ListingResult) -> RustBuffer {
    FfiConverterTypeS3ListingResult.lower(value)
}

/**
 * Metadata returned from an S3 HeadObject call.
 */
public struct S3ObjectMetadata: Equatable, Hashable {
    /**
     * The object's ETag.
     */
    public var etag: String?
    /**
     * The MIME content type.
     */
    public var contentType: String?
    /**
     * When the object was last modified.
     */
    public var lastModified: String?
    /**
     * The version ID (if bucket versioning is enabled).
     */
    public var versionId: String?
    /**
     * The object size in bytes.
     */
    public var contentLength: Int64
    /**
     * User-defined metadata key-value pairs.
     */
    public var metadata: [String: String]?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The object's ETag.
         */ etag: String?,
        /* 
            * The MIME content type.
            */ contentType: String?,
        /* 
            * When the object was last modified.
            */ lastModified: String?,
        /* 
            * The version ID (if bucket versioning is enabled).
            */ versionId: String?,
        /* 
            * The object size in bytes.
            */ contentLength: Int64,
        /* 
            * User-defined metadata key-value pairs.
            */ metadata: [String: String]?
    ) {
        self.etag = etag
        self.contentType = contentType
        self.lastModified = lastModified
        self.versionId = versionId
        self.contentLength = contentLength
        self.metadata = metadata
    }
}

#if compiler(>=6)
    extension S3ObjectMetadata: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeS3ObjectMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> S3ObjectMetadata {
        try S3ObjectMetadata(
            etag: FfiConverterOptionString.read(from: &buf),
            contentType: FfiConverterOptionString.read(from: &buf),
            lastModified: FfiConverterOptionString.read(from: &buf),
            versionId: FfiConverterOptionString.read(from: &buf),
            contentLength: FfiConverterInt64.read(from: &buf),
            metadata: FfiConverterOptionDictionaryStringString.read(from: &buf)
        )
    }

    public static func write(_ value: S3ObjectMetadata, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.etag, into: &buf)
        FfiConverterOptionString.write(value.contentType, into: &buf)
        FfiConverterOptionString.write(value.lastModified, into: &buf)
        FfiConverterOptionString.write(value.versionId, into: &buf)
        FfiConverterInt64.write(value.contentLength, into: &buf)
        FfiConverterOptionDictionaryStringString.write(value.metadata, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeS3ObjectMetadata_lift(_ buf: RustBuffer) throws -> S3ObjectMetadata {
    try FfiConverterTypeS3ObjectMetadata.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeS3ObjectMetadata_lower(_ value: S3ObjectMetadata) -> RustBuffer {
    FfiConverterTypeS3ObjectMetadata.lower(value)
}

/**
 * Summary of a single S3 object from a listing.
 */
public struct S3ObjectSummary: Equatable, Hashable {
    /**
     * The full S3 object key.
     */
    public var key: String
    /**
     * The object's ETag (entity tag for version/integrity checking).
     */
    public var etag: String?
    /**
     * When the object was last modified (ISO 8601 or S3 date format).
     */
    public var lastModified: String?
    /**
     * The object size in bytes.
     */
    public var size: Int64

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The full S3 object key.
         */ key: String,
        /* 
            * The object's ETag (entity tag for version/integrity checking).
            */ etag: String?,
        /* 
            * When the object was last modified (ISO 8601 or S3 date format).
            */ lastModified: String?,
        /* 
            * The object size in bytes.
            */ size: Int64
    ) {
        self.key = key
        self.etag = etag
        self.lastModified = lastModified
        self.size = size
    }
}

#if compiler(>=6)
    extension S3ObjectSummary: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeS3ObjectSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> S3ObjectSummary {
        try S3ObjectSummary(
            key: FfiConverterString.read(from: &buf),
            etag: FfiConverterOptionString.read(from: &buf),
            lastModified: FfiConverterOptionString.read(from: &buf),
            size: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: S3ObjectSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterOptionString.write(value.etag, into: &buf)
        FfiConverterOptionString.write(value.lastModified, into: &buf)
        FfiConverterInt64.write(value.size, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeS3ObjectSummary_lift(_ buf: RustBuffer) throws -> S3ObjectSummary {
    try FfiConverterTypeS3ObjectSummary.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeS3ObjectSummary_lower(_ value: S3ObjectSummary) -> RustBuffer {
    FfiConverterTypeS3ObjectSummary.lower(value)
}

/**
 * A JWT access token with expiration metadata.
 *
 * In the Swift codebase, `exp_date` is decoded from an ISO 8601 string into
 * a `Date`. Here we store it as a `String` for JSON compatibility and let
 * consumers parse it with chrono when needed.
 */
public struct Token: Equatable, Hashable {
    /**
     * The JWT access token string.
     */
    public var token: String
    /**
     * The token expiration as Unix timestamp (seconds).
     */
    public var exp: Int64
    /**
     * The token expiration as an ISO 8601 date string.
     */
    public var expDate: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The JWT access token string.
         */ token: String,
        /* 
            * The token expiration as Unix timestamp (seconds).
            */ exp: Int64,
        /* 
            * The token expiration as an ISO 8601 date string.
            */ expDate: String
    ) {
        self.token = token
        self.exp = exp
        self.expDate = expDate
    }
}

#if compiler(>=6)
    extension Token: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeToken: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Token {
        try Token(
            token: FfiConverterString.read(from: &buf),
            exp: FfiConverterInt64.read(from: &buf),
            expDate: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Token, into buf: inout [UInt8]) {
        FfiConverterString.write(value.token, into: &buf)
        FfiConverterInt64.write(value.exp, into: &buf)
        FfiConverterString.write(value.expDate, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeToken_lift(_ buf: RustBuffer) throws -> Token {
    try FfiConverterTypeToken.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeToken_lower(_ value: Token) -> RustBuffer {
    FfiConverterTypeToken.lower(value)
}

/**
 * Progress of a file transfer (upload or download).
 */
public struct TransferProgress: Equatable, Hashable {
    /**
     * Bytes transferred so far.
     */
    public var bytesTransferred: Int64
    /**
     * Total bytes expected (may be unknown for downloads).
     */
    public var totalBytes: Int64?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Bytes transferred so far.
         */ bytesTransferred: Int64,
        /* 
            * Total bytes expected (may be unknown for downloads).
            */ totalBytes: Int64?
    ) {
        self.bytesTransferred = bytesTransferred
        self.totalBytes = totalBytes
    }
}

#if compiler(>=6)
    extension TransferProgress: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransferProgress: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransferProgress {
        try TransferProgress(
            bytesTransferred: FfiConverterInt64.read(from: &buf),
            totalBytes: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TransferProgress, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.bytesTransferred, into: &buf)
        FfiConverterOptionInt64.write(value.totalBytes, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTransferProgress_lift(_ buf: RustBuffer) throws -> TransferProgress {
    try FfiConverterTypeTransferProgress.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTransferProgress_lower(_ value: TransferProgress) -> RustBuffer {
    FfiConverterTypeTransferProgress.lower(value)
}

/**
 * Unified error type covering auth, S3, HTTP, IO, and FFI error domains.
 */
public enum Ds3Error: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {
    /**
     * The provided URL is malformed.
     */
    case InvalidUrl(message: String)

    /**
     * The server returned an unexpected HTTP status.
     */
    case ServerError(message: String)

    /**
     * JSON serialization or deserialization failed.
     */
    case JsonError(message: String)

    /**
     * Encoding failure (e.g. string to bytes).
     */
    case Encoding(message: String)

    /**
     * The user is not logged in.
     */
    case LoggedOut(message: String)

    /**
     * The access token has expired.
     */
    case TokenExpired(message: String)

    /**
     * Two-factor authentication code is required.
     */
    case Missing2Fa(message: String)

    /**
     * Cookie extraction or parsing failed.
     */
    case CookieError(message: String)

    /**
     * The multipart upload ID is missing from the response.
     */
    case MissingUploadId(message: String)

    /**
     * The file data provided for upload is empty.
     */
    case EmptyFileData(message: String)

    /**
     * The ETag is missing from the S3 response.
     */
    case MissingETag(message: String)

    /**
     * Failed to parse an S3 response.
     */
    case ParseError(message: String)

    /**
     * Unable to open the local file for reading.
     */
    case UnableToOpenFile(message: String)

    /**
     * An I/O error occurred.
     */
    case IoError(message: String)

    /**
     * An HTTP transport error occurred.
     */
    case HttpError(message: String)

    /**
     * An S3 operation failed.
     */
    case S3Error(message: String)

    /**
     * An authentication operation failed.
     */
    case AuthError(message: String)

    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if compiler(>=6)
    extension Ds3Error: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDS3Error: FfiConverterRustBuffer {
    typealias SwiftType = Ds3Error

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Ds3Error {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .InvalidUrl(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .ServerError(
                message: FfiConverterString.read(from: &buf)
            )

        case 3: return try .JsonError(
                message: FfiConverterString.read(from: &buf)
            )

        case 4: return try .Encoding(
                message: FfiConverterString.read(from: &buf)
            )

        case 5: return try .LoggedOut(
                message: FfiConverterString.read(from: &buf)
            )

        case 6: return try .TokenExpired(
                message: FfiConverterString.read(from: &buf)
            )

        case 7: return try .Missing2Fa(
                message: FfiConverterString.read(from: &buf)
            )

        case 8: return try .CookieError(
                message: FfiConverterString.read(from: &buf)
            )

        case 9: return try .MissingUploadId(
                message: FfiConverterString.read(from: &buf)
            )

        case 10: return try .EmptyFileData(
                message: FfiConverterString.read(from: &buf)
            )

        case 11: return try .MissingETag(
                message: FfiConverterString.read(from: &buf)
            )

        case 12: return try .ParseError(
                message: FfiConverterString.read(from: &buf)
            )

        case 13: return try .UnableToOpenFile(
                message: FfiConverterString.read(from: &buf)
            )

        case 14: return try .IoError(
                message: FfiConverterString.read(from: &buf)
            )

        case 15: return try .HttpError(
                message: FfiConverterString.read(from: &buf)
            )

        case 16: return try .S3Error(
                message: FfiConverterString.read(from: &buf)
            )

        case 17: return try .AuthError(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Ds3Error, into buf: inout [UInt8]) {
        switch value {
        case .InvalidUrl(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .ServerError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        case .JsonError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(3))
        case .Encoding(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(4))
        case .LoggedOut(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(5))
        case .TokenExpired(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(6))
        case .Missing2Fa(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(7))
        case .CookieError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(8))
        case .MissingUploadId(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(9))
        case .EmptyFileData(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(10))
        case .MissingETag(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(11))
        case .ParseError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(12))
        case .UnableToOpenFile(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(13))
        case .IoError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(14))
        case .HttpError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(15))
        case .S3Error(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(16))
        case .AuthError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(17))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDS3Error_lift(_ buf: RustBuffer) throws -> Ds3Error {
    try FfiConverterTypeDS3Error.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDS3Error_lower(_ value: Ds3Error) -> RustBuffer {
    FfiConverterTypeDS3Error.lower(value)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionDictionaryStringString: FfiConverterRustBuffer {
    typealias SwiftType = [String: String]?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDictionaryStringString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDictionaryStringString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeAccountEmail: FfiConverterRustBuffer {
    typealias SwiftType = [AccountEmail]

    static func write(_ value: [AccountEmail], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAccountEmail.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AccountEmail] {
        let len: Int32 = try readInt(&buf)
        var seq = [AccountEmail]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeAccountEmail.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeIAMUser: FfiConverterRustBuffer {
    typealias SwiftType = [IamUser]

    static func write(_ value: [IamUser], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeIAMUser.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [IamUser] {
        let len: Int32 = try readInt(&buf)
        var seq = [IamUser]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeIAMUser.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeS3ObjectSummary: FfiConverterRustBuffer {
    typealias SwiftType = [S3ObjectSummary]

    static func write(_ value: [S3ObjectSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeS3ObjectSummary.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [S3ObjectSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [S3ObjectSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeS3ObjectSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ds3_models_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    return InitializationResult.ok
}()

/// Make the ensure init function public so that other modules which have external type references to
/// our types can call it.
public func uniffiEnsureDs3ModelsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
