// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(DS3CoreFFIFFI)
    import DS3CoreFFIFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ds3_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ds3_ffi_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    []
}

private func writeBytes(_ writer: inout [UInt8], _ byteArr: some Sequence<UInt8>) {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt(_ writer: inout [UInt8], _ value: some FixedWidthInteger) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}
/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: "Reading the requested value would read past the end of the buffer"
        case .incompleteData: "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: "The object in the handle map has been dropped already"
        case let .rustPanic(message): message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> some Swift.Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> some Swift.Error)?
) throws -> T {
    uniffiEnsureDs3FfiInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> some Swift.Error)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
private let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
private let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

private final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            doInsert(obj)
        }
    }

    /// Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

/// Public interface members begin here.
/// Magic number for the Rust proxy to call using the same mechanism as every other method,
/// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        try lift(readInt(&buf))
    }

    static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        try lift(readInt(&buf))
    }

    static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(readBytes(&buf, count: Int(len)))
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

/**
 * Cooperative cancellation handle shared between Swift caller and Rust ops.
 *
 * Backed by an `Arc<AtomicBool>` so the handle can be cloned and observed
 * from multiple threads with lock-free reads. Threat T-16-02-01 mitigation:
 * `Ordering::SeqCst` ensures cancel writes are immediately visible to all
 * readers.
 */
public protocol CancellationHandleProtocol: AnyObject, Sendable {
    /**
     * Requests cancellation. Idempotent and thread-safe.
     */
    func cancel()

    /**
     * Returns `true` once `cancel()` has been called.
     */
    func isCancelled() -> Bool
}
/**
 * Cooperative cancellation handle shared between Swift caller and Rust ops.
 *
 * Backed by an `Arc<AtomicBool>` so the handle can be cloned and observed
 * from multiple threads with lock-free reads. Threat T-16-02-01 mitigation:
 * `Ordering::SeqCst` ensures cancel writes are immediately visible to all
 * readers.
 */
open class CancellationHandle: CancellationHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    // Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public required init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may
    // be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there
    //     isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        try! rustCall { uniffi_ds3_ffi_fn_clone_cancellationhandle(self.handle, $0) }
    }
    /**
     * Creates a fresh handle in the "not cancelled" state.
     */
    public convenience init() {
        let handle =
            try! rustCall {
                uniffi_ds3_ffi_fn_constructor_cancellationhandle_new($0
                )
            }
        self.init(unsafeFromHandle: handle)
    }

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_ds3_ffi_fn_free_cancellationhandle(handle, $0) }
    }

    /**
     * Requests cancellation. Idempotent and thread-safe.
     */
    open func cancel() {
        try! rustCall {
            uniffi_ds3_ffi_fn_method_cancellationhandle_cancel(
                self.uniffiCloneHandle(), $0
            )
        }
    }

    /**
     * Returns `true` once `cancel()` has been called.
     */
    open func isCancelled() -> Bool {
        try! FfiConverterBool.lift(try! rustCall {
            uniffi_ds3_ffi_fn_method_cancellationhandle_is_cancelled(
                self.uniffiCloneHandle(), $0
            )
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCancellationHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CancellationHandle

    public static func lift(_ handle: UInt64) throws -> CancellationHandle {
        CancellationHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CancellationHandle) -> UInt64 {
        value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CancellationHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CancellationHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCancellationHandle_lift(_ handle: UInt64) throws -> CancellationHandle {
    try FfiConverterTypeCancellationHandle.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCancellationHandle_lower(_ value: CancellationHandle) -> UInt64 {
    FfiConverterTypeCancellationHandle.lower(value)
}

/**
 * Opaque session handle exposed to Swift via UniFFI.
 *
 * Wraps an `Arc<DS3Session>` for auth and HTTP operations, plus an optional
 * `DS3S3Client` for S3 operations (initialized separately after obtaining
 * API key credentials).
 */
public protocol Ds3SessionHandleProtocol: AnyObject, Sendable {
    /**
     * Returns the authenticated account information.
     */
    func accountInfo() throws -> Account

    /**
     * Initializes the S3 client for this session with the given credentials.
     *
     * Must be called before any S3 operation. Typically called after
     * `forge_iam_token` + `create_api_key` to obtain S3 credentials.
     */
    func connectS3(endpoint: String, accessKey: String, secretKey: String, region: String?) throws

    /**
     * Copies an S3 object within the same bucket.
     *
     * When `metadata` is `Some`, sets `MetadataDirective::Replace` and
     * applies the new metadata. When `None`, preserves the source object's
     * metadata (default `COPY` directive).
     */
    func copyObject(bucket: String, sourceKey: String, destKey: String, metadata: [String: String]?) throws

    /**
     * Creates a new API key for a given IAM user.
     */
    func createApiKey(userId: String, keyName: String, iamToken: String) throws -> Ds3ApiKey

    /**
     * Creates a .ds3keep folder marker for the given folder key.
     */
    func createFolderMarker(bucket: String, folderKey: String) throws

    /**
     * Returns a clone of the current session (token + refresh token).
     *
     * Used after login/refresh/forge so the Swift adapter can persist the
     * `AccountSession` to the App Group JSON (PATTERNS.md §"App Group
     * Persistence Boundary", D-04/D-06).
     */
    func currentSession() throws -> AccountSession

    /**
     * Deletes an API key by its access key ID.
     */
    func deleteApiKey(userId: String, apiKeyId: String, iamToken: String) throws

    /**
     * Deletes a single S3 object.
     */
    func deleteObject(bucket: String, key: String) throws

    /**
     * Deletes multiple S3 objects. Returns the count of successfully deleted objects.
     */
    func deleteObjects(bucket: String, keys: [String]) throws -> Int32

    /**
     * Downloads an S3 object to a local file path.
     *
     * `cancel_token` is currently unused for download (single-call GET); reserved
     * for future chunked-download cancellation. See CONTEXT D-20.
     */
    func downloadObject(
        bucket: String,
        key: String,
        filePath: String,
        progress: ProgressCallback?,
        cancelToken: CancellationHandle?
    ) throws -> S3DownloadResult

    /**
     * Downloads an S3 object directly to an in-memory `Vec<u8>`.
     *
     * Intended for small payloads (thumbnails, .ds3keep markers, metadata blobs).
     * For large files, use `download_object` which streams to a file path.
     */
    func downloadToMemory(bucket: String, key: String) throws -> Data

    /**
     * Forges an IAM-scoped token for the specified user ID.
     */
    func forgeIamToken(userId: String) throws -> Token

    /**
     * Lists all projects for the authenticated user.
     */
    func getProjects() throws -> [Project]

    /**
     * Returns metadata for a single S3 object (HeadObject).
     */
    func headObject(bucket: String, key: String) throws -> S3ObjectMetadata

    /**
     * Lists all buckets accessible with the current S3 credentials.
     */
    func listBuckets() throws -> [BucketInfo]

    /**
     * Lists objects in a bucket with optional prefix, delimiter, and pagination.
     */
    func listObjects(
        bucket: String,
        prefix: String?,
        delimiter: String?,
        maxKeys: Int32?,
        continuationToken: String?
    ) throws -> S3ListingResult

    /**
     * Loads API keys for a given IAM user.
     */
    func loadApiKeys(userId: String, iamToken: String) throws -> [Ds3ApiKey]

    /**
     * Generates a presigned PUT URL for a multipart upload part.
     *
     * `expires_in_seconds` must be in `1..=604_800` (7 days, AWS sigv4 limit).
     * Swift consumes the returned URL to upload a single part via
     * `URLRequest.httpMethod = "PUT"`.
     */
    func presignUploadPart(
        bucket: String,
        key: String,
        uploadId: String,
        partNumber: Int32,
        expiresInSeconds: Int64
    ) throws -> String

    /**
     * Probes whether a folder marker (.ds3keep) exists for the given folder key.
     */
    func probeFolderExists(bucket: String, folderKey: String) throws -> Bool

    /**
     * Refreshes the access token if expired.
     */
    func refreshToken() throws

    /**
     * Uploads an in-memory `Vec<u8>` to S3 with optional custom metadata.
     *
     * Metadata is sent as `x-amz-meta-*` headers. Empty `data` produces a
     * zero-byte object (`.ds3keep` folder marker shape).
     */
    func uploadFromMemory(bucket: String, key: String, data: Data, metadata: [String: String]) throws -> String?

    /**
     * Uploads a local file to S3. Returns the ETag on success (if provided by S3).
     *
     * Automatically uses multipart upload for files larger than 5MB. When
     * `cancel_token` is provided, multipart upload checks it between parts
     * and aborts cleanly on cancel.
     */
    func uploadObject(
        bucket: String,
        key: String,
        filePath: String,
        progress: ProgressCallback?,
        cancelToken: CancellationHandle?
    ) throws -> String?
}
/**
 * Opaque session handle exposed to Swift via UniFFI.
 *
 * Wraps an `Arc<DS3Session>` for auth and HTTP operations, plus an optional
 * `DS3S3Client` for S3 operations (initialized separately after obtaining
 * API key credentials).
 */
open class Ds3SessionHandle: Ds3SessionHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    // Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public required init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may
    // be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there
    //     isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        try! rustCall { uniffi_ds3_ffi_fn_clone_ds3sessionhandle(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_ds3_ffi_fn_free_ds3sessionhandle(handle, $0) }
    }

    /**
     * Authenticates with the Cubbit IAM server and returns a session handle.
     *
     * This is the primary entry point. Orchestrates: get_challenge -> sign ->
     * post_signin -> get_account_info.
     */
    public static func authenticate(
        email: String,
        password: String,
        tenantId: String?,
        coordinatorUrl: String?
    ) throws -> Ds3SessionHandle {
        try FfiConverterTypeDS3SessionHandle_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_constructor_ds3sessionhandle_authenticate(
                FfiConverterString.lower(email),
                FfiConverterString.lower(password),
                FfiConverterOptionString.lower(tenantId),
                FfiConverterOptionString.lower(coordinatorUrl), $0
            )
        })
    }

    /**
     * Authenticates with a 2FA code (for accounts with two-factor enabled).
     */
    public static func verify2fa(
        email: String,
        password: String,
        tfaCode: String,
        tenantId: String?,
        coordinatorUrl: String?
    ) throws -> Ds3SessionHandle {
        try FfiConverterTypeDS3SessionHandle_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_constructor_ds3sessionhandle_verify_2fa(
                FfiConverterString.lower(email),
                FfiConverterString.lower(password),
                FfiConverterString.lower(tfaCode),
                FfiConverterOptionString.lower(tenantId),
                FfiConverterOptionString.lower(coordinatorUrl), $0
            )
        })
    }

    /**
     * Returns the authenticated account information.
     */
    open func accountInfo() throws -> Account {
        try FfiConverterTypeAccount_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_account_info(
                self.uniffiCloneHandle(), $0
            )
        })
    }

    /**
     * Initializes the S3 client for this session with the given credentials.
     *
     * Must be called before any S3 operation. Typically called after
     * `forge_iam_token` + `create_api_key` to obtain S3 credentials.
     */
    open func connectS3(endpoint: String, accessKey: String, secretKey: String, region: String?) throws {
        try rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_connect_s3(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(endpoint),
                FfiConverterString.lower(accessKey),
                FfiConverterString.lower(secretKey),
                FfiConverterOptionString.lower(region), $0
            )
        }
    }

    /**
     * Copies an S3 object within the same bucket.
     *
     * When `metadata` is `Some`, sets `MetadataDirective::Replace` and
     * applies the new metadata. When `None`, preserves the source object's
     * metadata (default `COPY` directive).
     */
    open func copyObject(bucket: String, sourceKey: String, destKey: String, metadata: [String: String]?) throws {
        try rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_copy_object(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(sourceKey),
                FfiConverterString.lower(destKey),
                FfiConverterOptionDictionaryStringString.lower(metadata), $0
            )
        }
    }

    /**
     * Creates a new API key for a given IAM user.
     */
    open func createApiKey(userId: String, keyName: String, iamToken: String) throws -> Ds3ApiKey {
        try FfiConverterTypeDS3ApiKey_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_create_api_key(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(userId),
                FfiConverterString.lower(keyName),
                FfiConverterString.lower(iamToken), $0
            )
        })
    }

    /**
     * Creates a .ds3keep folder marker for the given folder key.
     */
    open func createFolderMarker(bucket: String, folderKey: String) throws {
        try rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_create_folder_marker(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(folderKey), $0
            )
        }
    }

    /**
     * Returns a clone of the current session (token + refresh token).
     *
     * Used after login/refresh/forge so the Swift adapter can persist the
     * `AccountSession` to the App Group JSON (PATTERNS.md §"App Group
     * Persistence Boundary", D-04/D-06).
     */
    open func currentSession() throws -> AccountSession {
        try FfiConverterTypeAccountSession_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_current_session(
                self.uniffiCloneHandle(), $0
            )
        })
    }

    /**
     * Deletes an API key by its access key ID.
     */
    open func deleteApiKey(userId: String, apiKeyId: String, iamToken: String) throws {
        try rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_delete_api_key(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(userId),
                FfiConverterString.lower(apiKeyId),
                FfiConverterString.lower(iamToken), $0
            )
        }
    }

    /**
     * Deletes a single S3 object.
     */
    open func deleteObject(bucket: String, key: String) throws {
        try rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_delete_object(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(key), $0
            )
        }
    }

    /**
     * Deletes multiple S3 objects. Returns the count of successfully deleted objects.
     */
    open func deleteObjects(bucket: String, keys: [String]) throws -> Int32 {
        try FfiConverterInt32.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_delete_objects(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterSequenceString.lower(keys), $0
            )
        })
    }

    /**
     * Downloads an S3 object to a local file path.
     *
     * `cancel_token` is currently unused for download (single-call GET); reserved
     * for future chunked-download cancellation. See CONTEXT D-20.
     */
    open func downloadObject(
        bucket: String,
        key: String,
        filePath: String,
        progress: ProgressCallback?,
        cancelToken: CancellationHandle?
    ) throws -> S3DownloadResult {
        try FfiConverterTypeS3DownloadResult_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_download_object(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(key),
                FfiConverterString.lower(filePath),
                FfiConverterOptionCallbackInterfaceProgressCallback.lower(progress),
                FfiConverterOptionTypeCancellationHandle.lower(cancelToken), $0
            )
        })
    }

    /**
     * Downloads an S3 object directly to an in-memory `Vec<u8>`.
     *
     * Intended for small payloads (thumbnails, .ds3keep markers, metadata blobs).
     * For large files, use `download_object` which streams to a file path.
     */
    open func downloadToMemory(bucket: String, key: String) throws -> Data {
        try FfiConverterData.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_download_to_memory(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(key), $0
            )
        })
    }

    /**
     * Forges an IAM-scoped token for the specified user ID.
     */
    open func forgeIamToken(userId: String) throws -> Token {
        try FfiConverterTypeToken_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_forge_iam_token(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(userId), $0
            )
        })
    }

    /**
     * Lists all projects for the authenticated user.
     */
    open func getProjects() throws -> [Project] {
        try FfiConverterSequenceTypeProject.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_get_projects(
                self.uniffiCloneHandle(), $0
            )
        })
    }

    /**
     * Returns metadata for a single S3 object (HeadObject).
     */
    open func headObject(bucket: String, key: String) throws -> S3ObjectMetadata {
        try FfiConverterTypeS3ObjectMetadata_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_head_object(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(key), $0
            )
        })
    }

    /**
     * Lists all buckets accessible with the current S3 credentials.
     */
    open func listBuckets() throws -> [BucketInfo] {
        try FfiConverterSequenceTypeBucketInfo.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_list_buckets(
                self.uniffiCloneHandle(), $0
            )
        })
    }

    /**
     * Lists objects in a bucket with optional prefix, delimiter, and pagination.
     */
    open func listObjects(
        bucket: String,
        prefix: String?,
        delimiter: String?,
        maxKeys: Int32?,
        continuationToken: String?
    ) throws -> S3ListingResult {
        try FfiConverterTypeS3ListingResult_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_list_objects(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterOptionString.lower(prefix),
                FfiConverterOptionString.lower(delimiter),
                FfiConverterOptionInt32.lower(maxKeys),
                FfiConverterOptionString.lower(continuationToken), $0
            )
        })
    }

    /**
     * Loads API keys for a given IAM user.
     */
    open func loadApiKeys(userId: String, iamToken: String) throws -> [Ds3ApiKey] {
        try FfiConverterSequenceTypeDS3ApiKey.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_load_api_keys(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(userId),
                FfiConverterString.lower(iamToken), $0
            )
        })
    }

    /**
     * Generates a presigned PUT URL for a multipart upload part.
     *
     * `expires_in_seconds` must be in `1..=604_800` (7 days, AWS sigv4 limit).
     * Swift consumes the returned URL to upload a single part via
     * `URLRequest.httpMethod = "PUT"`.
     */
    open func presignUploadPart(
        bucket: String,
        key: String,
        uploadId: String,
        partNumber: Int32,
        expiresInSeconds: Int64
    ) throws -> String {
        try FfiConverterString.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_presign_upload_part(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(key),
                FfiConverterString.lower(uploadId),
                FfiConverterInt32.lower(partNumber),
                FfiConverterInt64.lower(expiresInSeconds), $0
            )
        })
    }

    /**
     * Probes whether a folder marker (.ds3keep) exists for the given folder key.
     */
    open func probeFolderExists(bucket: String, folderKey: String) throws -> Bool {
        try FfiConverterBool.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_probe_folder_exists(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(folderKey), $0
            )
        })
    }

    /**
     * Refreshes the access token if expired.
     */
    open func refreshToken() throws {
        try rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_refresh_token(
                self.uniffiCloneHandle(), $0
            )
        }
    }

    /**
     * Uploads an in-memory `Vec<u8>` to S3 with optional custom metadata.
     *
     * Metadata is sent as `x-amz-meta-*` headers. Empty `data` produces a
     * zero-byte object (`.ds3keep` folder marker shape).
     */
    open func uploadFromMemory(bucket: String, key: String, data: Data, metadata: [String: String]) throws -> String? {
        try FfiConverterOptionString.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_upload_from_memory(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(key),
                FfiConverterData.lower(data),
                FfiConverterDictionaryStringString.lower(metadata), $0
            )
        })
    }

    /**
     * Uploads a local file to S3. Returns the ETag on success (if provided by S3).
     *
     * Automatically uses multipart upload for files larger than 5MB. When
     * `cancel_token` is provided, multipart upload checks it between parts
     * and aborts cleanly on cancel.
     */
    open func uploadObject(
        bucket: String,
        key: String,
        filePath: String,
        progress: ProgressCallback?,
        cancelToken: CancellationHandle?
    ) throws -> String? {
        try FfiConverterOptionString.lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
            uniffi_ds3_ffi_fn_method_ds3sessionhandle_upload_object(
                self.uniffiCloneHandle(),
                FfiConverterString.lower(bucket),
                FfiConverterString.lower(key),
                FfiConverterString.lower(filePath),
                FfiConverterOptionCallbackInterfaceProgressCallback.lower(progress),
                FfiConverterOptionTypeCancellationHandle.lower(cancelToken), $0
            )
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDS3SessionHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Ds3SessionHandle

    public static func lift(_ handle: UInt64) throws -> Ds3SessionHandle {
        Ds3SessionHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Ds3SessionHandle) -> UInt64 {
        value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Ds3SessionHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Ds3SessionHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDS3SessionHandle_lift(_ handle: UInt64) throws -> Ds3SessionHandle {
    try FfiConverterTypeDS3SessionHandle.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDS3SessionHandle_lower(_ value: Ds3SessionHandle) -> UInt64 {
    FfiConverterTypeDS3SessionHandle.lower(value)
}

/**
 * UniFFI callback interface for reporting transfer progress.
 *
 * Swift consumers implement this trait and pass an instance to upload/download
 * methods. UniFFI generates the necessary bridging code automatically.
 */
public protocol ProgressCallback: AnyObject, Sendable {
    /**
     * Called periodically during a transfer with the current progress.
     *
     * - `bytes_transferred`: number of bytes transferred so far
     * - `total_bytes`: total expected bytes (-1 if unknown)
     */
    func onProgress(bytesTransferred: Int64, totalBytes: Int64)
}

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceProgressCallback {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    ///
    /// Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceProgressCallback = .init(
        uniffiFree: { (uniffiHandle: UInt64) in
            do {
                try FfiConverterCallbackInterfaceProgressCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ProgressCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceProgressCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ProgressCallback: handle missing in uniffiClone")
            }
        },
        onProgress: { (
            uniffiHandle: UInt64,
            bytesTransferred: Int64,
            totalBytes: Int64,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressCallback.handleMap
                    .get(handle: uniffiHandle)
                else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onProgress(
                    bytesTransferred: FfiConverterInt64.lift(bytesTransferred),
                    totalBytes: FfiConverterInt64.lift(totalBytes)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    /// Rust stores this pointer for future callback invocations, so it must live
    /// for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceProgressCallback> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceProgressCallback>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitProgressCallback() {
    uniffi_ds3_ffi_fn_init_callback_vtable_progresscallback(UniffiCallbackInterfaceProgressCallback.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private enum FfiConverterCallbackInterfaceProgressCallback {
    fileprivate static let handleMap = UniffiHandleMap<ProgressCallback>()
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceProgressCallback: FfiConverter {
    typealias SwiftType = ProgressCallback
    typealias FfiType = UInt64

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        handleMap.insert(obj: v)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceProgressCallback_lift(_ handle: UInt64) throws -> ProgressCallback {
    try FfiConverterCallbackInterfaceProgressCallback.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceProgressCallback_lower(_ v: ProgressCallback) -> UInt64 {
    FfiConverterCallbackInterfaceProgressCallback.lower(v)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeCancellationHandle: FfiConverterRustBuffer {
    typealias SwiftType = CancellationHandle?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCancellationHandle.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCancellationHandle.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionCallbackInterfaceProgressCallback: FfiConverterRustBuffer {
    typealias SwiftType = ProgressCallback?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceProgressCallback.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceProgressCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionDictionaryStringString: FfiConverterRustBuffer {
    typealias SwiftType = [String: String]?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDictionaryStringString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDictionaryStringString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeBucketInfo: FfiConverterRustBuffer {
    typealias SwiftType = [BucketInfo]

    static func write(_ value: [BucketInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBucketInfo.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BucketInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [BucketInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeBucketInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeDS3ApiKey: FfiConverterRustBuffer {
    typealias SwiftType = [Ds3ApiKey]

    static func write(_ value: [Ds3ApiKey], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDS3ApiKey.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Ds3ApiKey] {
        let len: Int32 = try readInt(&buf)
        var seq = [Ds3ApiKey]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeDS3ApiKey.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeProject: FfiConverterRustBuffer {
    typealias SwiftType = [Project]

    static func write(_ value: [Project], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeProject.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Project] {
        let len: Int32 = try readInt(&buf)
        var seq = [Project]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeProject.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
/**
 * Computes the diff between local and remote file tree snapshots.
 *
 * Both `local_json` and `remote_json` are JSON strings representing
 * `HashMap<String, Option<String>>` (key -> optional ETag).
 */
public func computeDiff(localJson: String, remoteJson: String) throws -> DiffResultRecord {
    try FfiConverterTypeDiffResultRecord_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
        uniffi_ds3_ffi_fn_func_compute_diff(
            FfiConverterString.lower(localJson),
            FfiConverterString.lower(remoteJson), $0
        )
    })
}
/**
 * Generates a conflict copy key from the original key and hostname.
 *
 * If `nonce` is `None`, a random 4-character hex nonce is generated.
 */
public func conflictKey(originalKey: String, hostname: String, nonce: String?) -> String {
    try! FfiConverterString.lift(try! rustCall {
        uniffi_ds3_ffi_fn_func_conflict_key(
            FfiConverterString.lower(originalKey),
            FfiConverterString.lower(hostname),
            FfiConverterOptionString.lower(nonce), $0
        )
    })
}
/**
 * Returns the numeric error code matching a [`DS3Error`] Display string.
 *
 * The UniFFI `flat_error` attribute on `DS3Error` collapses all enum variants
 * to a `(message: String)` shape on the Swift side, so the Swift adapter can
 * only inspect the error's stringified Display when it catches one
 * (FFI-AUDIT.md A1). This helper maps that Display string back to the
 * numeric code defined by `DS3Error::code()` so per-adapter translation
 * tables (PATTERNS.md Pattern 3) can dispatch on integers 1001..=3004.
 *
 * Returns `-1` for inputs that don't match any known variant (the Swift
 * adapter maps this to a generic "unknown" case).
 */
public func ds3ErrorCode(message: String) -> Int32 {
    try! FfiConverterInt32.lift(try! rustCall {
        uniffi_ds3_ffi_fn_func_ds3_error_code(
            FfiConverterString.lower(message), $0
        )
    })
}
/**
 * Retrieves an auth challenge from the IAM server.
 */
public func getChallenge(email: String, tenantId: String?, coordinatorUrl: String?) throws -> Challenge {
    try FfiConverterTypeChallenge_lift(rustCallWithError(FfiConverterTypeDS3Error_lift) {
        uniffi_ds3_ffi_fn_func_get_challenge(
            FfiConverterString.lower(email),
            FfiConverterOptionString.lower(tenantId),
            FfiConverterOptionString.lower(coordinatorUrl), $0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ds3_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_ds3_ffi_checksum_func_compute_diff() != 1146 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_func_conflict_key() != 41470 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_func_ds3_error_code() != 58643 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_func_get_challenge() != 14364 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_cancellationhandle_cancel() != 35292 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_cancellationhandle_is_cancelled() != 59677 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_account_info() != 44131 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_connect_s3() != 33655 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_copy_object() != 27808 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_create_api_key() != 21954 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_create_folder_marker() != 17365 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_current_session() != 14493 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_delete_api_key() != 910 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_delete_object() != 63439 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_delete_objects() != 33026 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_download_object() != 55647 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_download_to_memory() != 29178 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_forge_iam_token() != 60725 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_get_projects() != 24484 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_head_object() != 20975 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_list_buckets() != 3368 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_list_objects() != 7766 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_load_api_keys() != 8257 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_presign_upload_part() != 18904 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_probe_folder_exists() != 22319 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_refresh_token() != 20179 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_upload_from_memory() != 47842 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_ds3sessionhandle_upload_object() != 62369 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_constructor_cancellationhandle_new() != 9464 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_constructor_ds3sessionhandle_authenticate() != 17499 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_constructor_ds3sessionhandle_verify_2fa() != 2887 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ds3_ffi_checksum_method_progresscallback_on_progress() != 50762 {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitProgressCallback()
    uniffiEnsureDs3ModelsInitialized()
    return InitializationResult.ok
}()

/// Make the ensure init function public so that other modules which have external type references to
/// our types can call it.
public func uniffiEnsureDs3FfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
