[package]
name = "ds3-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "ds3_ffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
ds3-models = { path = "../ds3-models" }
ds3-auth = { path = "../ds3-auth" }
ds3-http = { path = "../ds3-http" }
ds3-s3 = { path = "../ds3-s3" }
ds3-sync = { path = "../ds3-sync" }
tokio = { workspace = true }
uniffi = "0.29"

[build-dependencies]
uniffi = { version = "0.29", features = ["build"] }
