// DS3CoreFFI Swift Integration Test Harness
//
// Tests the UniFFI-generated Swift bindings against real Cubbit S3.
// Requires DS3_TEST_EMAIL, DS3_TEST_PASSWORD, DS3_TEST_BUCKET env vars.
//
// The generated DS3CoreFFI.swift file must be copied into Sources/ before
// building (it's generated by the XCFramework build script).
//
// Run: cd core/tests/swift_harness && swift run

import Foundation

// MARK: - Helpers

func env(_ name: String) -> String? {
    ProcessInfo.processInfo.environment[name]
}

func require(_ name: String) -> String {
    guard let value = env(name), !value.isEmpty else {
        print("SKIP: \(name) not set")
        exit(0)
    }
    return value
}

func assert(_ condition: Bool, _ message: String, file: String = #file, line: Int = #line) {
    guard condition else {
        print("FAIL [\(file):\(line)]: \(message)")
        exit(1)
    }
}

var testCount = 0
var passCount = 0

func test(_ name: String, _ body: () throws -> Void) {
    testCount += 1
    do {
        try body()
        passCount += 1
        print("  PASS: \(name)")
    } catch {
        print("  FAIL: \(name) -- \(error)")
        exit(1)
    }
}

func testAsync(_ name: String, _ body: () async throws -> Void) async {
    testCount += 1
    do {
        try await body()
        passCount += 1
        print("  PASS: \(name)")
    } catch {
        print("  FAIL: \(name) -- \(error)")
        exit(1)
    }
}

// MARK: - Test execution

print("DS3CoreFFI Swift Integration Tests")
print("===================================")

let email = require("DS3_TEST_EMAIL")
let password = require("DS3_TEST_PASSWORD")
let bucket = require("DS3_TEST_BUCKET")

// Test 1: Authenticate
test("authenticate") {
    let session = try DS3SessionHandle.authenticate(
        email: email,
        password: password,
        tenantId: nil,
        coordinatorUrl: nil
    )

    let account = try session.accountInfo()
    assert(!account.tenantId.isEmpty, "tenant_id must be non-empty")
    assert(!account.id.isEmpty, "account id must be non-empty")
    print("    Authenticated as: \(account.firstName) \(account.lastName)")

    // Test 2: Refresh token
    test("refresh_token") {
        try session.refreshToken()
    }

    // Test 3: Forge IAM token
    test("forge_iam_token") {
        let iamToken = try session.forgeIamToken(userId: account.id)
        assert(!iamToken.token.isEmpty, "IAM token must be non-empty")
        assert(iamToken.exp > 0, "IAM token exp must be > 0")

        // Test 4: Get projects
        test("get_projects") {
            let projects = try session.getProjects()
            assert(!projects.isEmpty, "should have at least one project")
            print("    Found \(projects.count) project(s)")
        }

        // Test 5: Load API keys and connect S3
        test("connect_s3_and_list") {
            let keys = try session.loadApiKeys(userId: account.id, iamToken: iamToken.token)
            assert(!keys.isEmpty, "should have at least one API key")

            let apiKey = keys[0]
            try session.connectS3(
                endpoint: account.endpointGateway,
                accessKey: apiKey.apiKey,
                secretKey: apiKey.secretKey ?? "",
                region: nil
            )

            // Test 6: List objects
            let listing = try session.listObjects(
                bucket: bucket,
                prefix: nil,
                delimiter: nil,
                maxKeys: 10,
                continuationToken: nil
            )
            print("    Listed \(listing.objects.count) object(s)")
        }

        // Test 7: Upload, download, delete cycle
        test("upload_download_delete") {
            let testPrefix = "ds3-swift-test-\(UUID().uuidString)/"
            let testKey = "\(testPrefix)test-file.txt"
            let testContent = "Hello from Swift integration test!"

            // Create temp file
            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("ds3-swift-test")
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

            let uploadPath = tempDir.appendingPathComponent("upload.txt")
            try testContent.write(to: uploadPath, atomically: true, encoding: .utf8)

            // Upload
            let etag = try session.uploadObject(
                bucket: bucket,
                key: testKey,
                filePath: uploadPath.path,
                progress: nil
            )
            assert(etag != nil, "upload should return an ETag")

            // Download
            let downloadPath = tempDir.appendingPathComponent("download.txt")
            let downloadResult = try session.downloadObject(
                bucket: bucket,
                key: testKey,
                filePath: downloadPath.path,
                progress: nil
            )
            assert(
                downloadResult.contentLength == Int64(testContent.utf8.count),
                "content length should match"
            )

            let downloaded = try String(contentsOf: downloadPath, encoding: .utf8)
            assert(downloaded == testContent, "downloaded content should match")

            // Delete
            try session.deleteObject(bucket: bucket, key: testKey)

            // Cleanup
            try? FileManager.default.removeItem(at: tempDir)
        }
    }
}

// Test 8: Compute diff (static, no session needed)
test("compute_diff") {
    let localJson = """
    {"file1.txt": "etag1", "file2.txt": "etag2", "deleted.txt": "etag3"}
    """
    let remoteJson = """
    {"file1.txt": "etag1", "file2.txt": "etag2-modified", "new.txt": "etag4"}
    """

    let result = try computeDiff(localJson: localJson, remoteJson: remoteJson)
    // The diff should detect changes
    assert(
        !result.downloads.isEmpty || !result.uploads.isEmpty || !result.conflicts.isEmpty,
        "diff should detect at least one change"
    )
}

// Test 9: Conflict key (static, no session needed)
test("conflict_key") {
    let key = conflictKey(
        originalKey: "documents/report.pdf",
        hostname: "test-mac",
        nonce: "abcd"
    )
    assert(key.contains("report"), "conflict key should contain original name")
    assert(key.contains("test-mac"), "conflict key should contain hostname")
}

print("")
print("All Swift integration tests passed (\(passCount)/\(testCount))")
